## YAML Template.
---
#Language: de-de
Language: en-us
SyncBlockSetter:
  Ticks: 2
DBSaver:
  Ticks: 18000
ProjectionAreas:
  Ticks: 10
DynMap:
  Ticks: 40
WorldClassifications:
  -
    name: empty_flat
    generateStructures: true
    generator:
    seed: 42
    type: FLAT
    environment: NORMAL
    spawnMonsters: false
    spawnAnimals: false
    difficulty: NORMAL
    ownInventory: true
    inventoryName: creative
    gameMode: CREATIVE
    playerVsPlayer: false
  -
    name: empty_nether
    generateStructures: true
    generator:
    seed: 42
    type: NORMAL
    environment: NETHER
    spawnMonsters: false
    spawnAnimals: false
    difficulty: NORMAL
    ownInventory: true
    inventoryName: creative
    gameMode: CREATIVE
    playerVsPlayer: false
  -
    name: empty_normal
    generateStructures: true
    generator:
    seed: 42
    type: NORMAL
    environment: NORMAL
    spawnMonsters: false
    spawnAnimals: false
    difficulty: NORMAL
    ownInventory: true
    inventoryName: creative
    gameMode: CREATIVE
    playerVsPlayer: false
  -
    name: empty_large
    generateStructures: true
    generator:
    type: LARGE_BIOMES
    environment: NORMAL
    spawnMonsters: false
    spawnAnimals: false
    difficulty: NORMAL
    ownInventory: true
    inventoryName: creative
    gameMode: CREATIVE
    playerVsPlayer: false
    