## YAML Template.
name: MAHN42-Framework
main: com.mahn42.framework.Framework
version: 0.48
commands:
   fw_bd_dump:
      description: only for testing, dumps building descriptions.
      usage: /fw_bd_dump descname
      permission: fw.bd_dump
      permission-message: You don't have permission
   fw_bd_create:
      description: only for testing, create a building for a given building description.
      usage: /fw_bd_create descname
      permission: fw.bd_create
      permission-message: You don't have permission
   fw_bd_detect:
      description: only for testing, detect a building for a given building description.
      usage: /fw_bd_detect descname
      permission: fw.bd_detect
      permission-message: You don't have permission
   fw_set_spawn:
      description: set the worlds spawn point to the player location.
      usage: /fw_set_sawn
      permission: fw.set_spawn
      permission-message: You don't have permission
   fw_save:
      description: save the data to disk. 
      usage: /fw_save
      permission: fw.save
      permission-message: You don't have permission
   fw_debug:
      description: set or show the debug option. 
      usage: /fw_debug <optionname> [true|false]
      permission: fw.debug
      permission-message: You don't have permission
   fw_markpos:
      description: set current player position for given marker. 
      usage: /fw_markpos <markername>
      permission: fw.markpos
      permission-message: You don't have permission
   fw_area_save:
      description: save area given by marker 1 and 2 to given file. 
      usage: /fw_area_save <filename>
      permission: fw.area_save
      permission-message: You don't have permission
   fw_area_load:
      description: load area to player location. 
      usage: /fw_area_load <filename>
      permission: fw.area_load
      permission-message: You don't have permission
permissions:
    fw.*:
        description: Gives access to all framework commands
        children:
            fw.bd_dump: true
            fw.bd_create: true
            fw.bd_detect: true
            fw.set_spawn: true
            fw.save: true
            fw.debug: true
            fw.markpos: true
            fw.area_save: true
            fw.area_load: true
    fw.bd_dump:
        description: Allows you to dump building descriptions
        default: false
    fw.bd_create:
        description: Allows you to create a building based on a building description
        default: false
    fw.bd_detect:
        description: Allows you to detect a building based on a building description
        default: false
    fw.set_spawn:
        description: Allows you to set the spawn point of the world
        default: false
    fw.save:
        description: Allows you to save data to disk
        default: false
    fw.debug:
        description: Allows you to set debug option
        default: false
    fw.markpos:
        description: Allows you to set a marker position
        default: false
    fw.area_save:
        description: Allows you to save an area
        default: false
    fw.area_load:
        description: Allows you to load an area
        default: false
