## YAML Template.
name: MAHN42-Framework
main: com.mahn42.framework.Framework
version: 0.53
softdepend: [dynmap]
commands:
   fw_bd_dump:
      description: only for testing, dumps building descriptions.
      usage: /fw_bd_dump <descname>
      permission: fw.bd_dump
      permission-message: You don't have permission
   fw_bd_create:
      description: only for testing, create a building for a given building description.
      usage: /fw_bd_create <descname>
      permission: fw.bd_create
      permission-message: You don't have permission
   fw_bd_createfromarea:
      description: only for testing, create a buildingdescription for a given area.
      usage: /fw_bd_createfromarea <descname> <areafilename>
      aliases: bd_cfa
      permission: fw.bd_createfromarea
      permission-message: You don't have permission
   fw_bd_detect:
      description: only for testing, detect a building for a given building description.
      usage: /fw_bd_detect <descname>
      permission: fw.bd_detect
      permission-message: You don't have permission
   fw_set_spawn:
      description: set the worlds spawn point to the player location.
      usage: /fw_set_sawn
      permission: fw.set_spawn
      permission-message: You don't have permission
   fw_save:
      description: save the data to disk. 
      usage: /fw_save
      permission: fw.save
      permission-message: You don't have permission
   fw_debug:
      description: set or show the debug option. 
      usage: /fw_debug <optionname> [true|false]
      permission: fw.debug
      permission-message: You don't have permission
   fw_world_create:
      description: create a new world. 
      usage: /fw_world_create <worldname> [worldclass]
      aliases: [newworld, createworld]
      permission: fw.world_create
      permission-message: You don't have permission
   fw_world_remove:
      description: remove a new world. 
      usage: /fw_world_remove <worldname>
      aliases: removeworld
      permission: fw.world_remove
      permission-message: You don't have permission
   fw_world_clist:
      description: list all registered worldclassifications. 
      usage: /fw_world_clist
      permission: fw.world_clist
      permission-message: You don't have permission
   fw_world_list:
      description: list all worlds. 
      usage: /fw_world_list
      permission: fw.world_list
      permission-message: You don't have permission
   fw_world_set:
      description: set property for world configuration. 
      usage: /fw_world_set name value [worldname]
      permission: fw.world_set
      permission-message: You don't have permission
   fw_world_regenerate:
      description: regenerate a region of a world. 
      usage: /fw_world_regenerate [<x> <z> <radius> <worldname>] | [<radius> [<worldname>]]
      aliases: wreg
      permission: fw.world_regenerate
      permission-message: You don't have permission
   fw_world_pinv:
      description: list player inventory for player in a world. 
      usage: /fw_world_pinv [<playername> [<worldname>]]
      aliases: wpinv
      permission: fw.world_pinv
      permission-message: You don't have permission
   fw_marker_list:
      description: list markers with name or in area of world. 
      usage: /fw_marker_list <markername>|(<from> - <to>) [<worldname>]
      aliases: mlist
      permission: fw.marker_list
      permission-message: You don't have permission
   fw_tp:
      description: teleport to position and a world. 
      usage: /fw_tp [<worldname>] [<x> <y> <z>]
      permission: fw.tp
      permission-message: You don't have permission
   fw_chunk_regenerate:
      description: regenerate chunks in the world. 
      usage: /fw_chunk_regenerate [<chunkradius>]
      permission: fw.chunk_regenerate
      permission-message: You don't have permission
   fw_test:
      description: for testing. 
      usage: /fw_test playerspawn <name>
      permission: fw.test
      permission-message: You don't have permission
permissions:
    fw.*:
        description: Gives access to all framework commands
        children:
            fw.bd_dump: true
            fw.bd_create: true
            fw.bd_createfromarea: true
            fw.bd_detect: true
            fw.set_spawn: true
            fw.save: true
            fw.debug: true
            fw.markpos: true
            fw.area_save: true
            fw.area_load: true
            fw.area_delete: true
            fw.area_remove: true
            fw.we_fill: true
            fw.world_create: true
            fw.world_remove: true
            fw.world_regenerate: true
            fw.world_list: true
            fw.world_clist: true
            fw.world_set: true
            fw.world_pinv: true
            fw.marker_list: true
            fw.tp: true
            fw.chunk_regenerate: true
            fw.test: true
    fw.bd_dump:
        description: Allows you to dump building descriptions
        default: false
    fw.bd_create:
        description: Allows you to create a building based on a building description
        default: false
    fw.bd_createfromarea:
        description: Allows you to create a building description based on a area
        default: false
    fw.bd_detect:
        description: Allows you to detect a building based on a building description
        default: false
    fw.set_spawn:
        description: Allows you to set the spawn point of the world
        default: false
    fw.save:
        description: Allows you to save data to disk
        default: false
    fw.debug:
        description: Allows you to set debug option
        default: false
    fw.world_create:
        description: Allows you to create new world
        default: false
    fw.world_remove:
        description: Allows you to remove a world
        default: false
    fw.world_regenerate:
        description: Allows you to regenerate a region of a world
        default: false
    fw.world_clist:
        description: Allows you to list all registered worldclassifications
        default: false
    fw.world_list:
        description: Allows you to list all worlds
        default: false
    fw.world_set:
        description: Allows you to set properties of a world
        default: false
    fw.world_pinv:
        description: Allows you to list a playerinventory of a world
        default: false
    fw.marker_list:
        description: Allows you to list markers of a world
        default: true
    fw.tp:
        description: Allows you to teleport to position in a world
        default: false
    fw.chunk_regenerate:
        description: Allows you regenerate chunks in the world
        default: false
    fw.test:
        description: Allows you to test something
        default: false
