## YAML Template.
name: MAHN42-Framework
main: com.mahn42.framework.Framework
version: 0.49
commands:
   fw_bd_dump:
      description: only for testing, dumps building descriptions.
      usage: /fw_bd_dump descname
      permission: fw.bd_dump
      permission-message: You don't have permission
   fw_bd_create:
      description: only for testing, create a building for a given building description.
      usage: /fw_bd_create descname
      permission: fw.bd_create
      permission-message: You don't have permission
   fw_bd_detect:
      description: only for testing, detect a building for a given building description.
      usage: /fw_bd_detect descname
      permission: fw.bd_detect
      permission-message: You don't have permission
   fw_set_spawn:
      description: set the worlds spawn point to the player location.
      usage: /fw_set_sawn
      permission: fw.set_spawn
      permission-message: You don't have permission
   fw_save:
      description: save the data to disk. 
      usage: /fw_save
      permission: fw.save
      permission-message: You don't have permission
   fw_debug:
      description: set or show the debug option. 
      usage: /fw_debug <optionname> [true|false]
      permission: fw.debug
      permission-message: You don't have permission
   fw_world_create:
      description: create a new world. 
      usage: /fw_world_create <worldname> [worldclass]
      aliases: newworld
      permission: fw.world_create
      permission-message: You don't have permission
   fw_world_remove:
      description: remove a new world. 
      usage: /fw_world_remove <worldname>
      aliases: removeworld
      permission: fw.world_remove
      permission-message: You don't have permission
   fw_world_clist:
      description: list all registered worldclassifications. 
      usage: /fw_world_clist
      permission: fw.world_clist
      permission-message: You don't have permission
   fw_world_list:
      description: list all worlds. 
      usage: /fw_world_list
      permission: fw.world_list
      permission-message: You don't have permission
   fw_tp:
      description: teleport to position and a world. 
      usage: /fw_tp [<worldname>] [<x> <y> <z>]
      permission: fw.tp
      permission-message: You don't have permission
permissions:
    fw.*:
        description: Gives access to all framework commands
        children:
            fw.bd_dump: true
            fw.bd_create: true
            fw.bd_detect: true
            fw.set_spawn: true
            fw.save: true
            fw.debug: true
            fw.markpos: true
            fw.area_save: true
            fw.area_load: true
            fw.area_delete: true
            fw.area_remove: true
            fw.we_fill: true
            fw.world_create: true
            fw.world_remove: true
            fw.world_list: true
            fw.world_clist: true
            fw.tp: true
    fw.bd_dump:
        description: Allows you to dump building descriptions
        default: false
    fw.bd_create:
        description: Allows you to create a building based on a building description
        default: false
    fw.bd_detect:
        description: Allows you to detect a building based on a building description
        default: false
    fw.set_spawn:
        description: Allows you to set the spawn point of the world
        default: false
    fw.save:
        description: Allows you to save data to disk
        default: false
    fw.debug:
        description: Allows you to set debug option
        default: false
    fw.world_create:
        description: Allows you to create new world
        default: false
    fw.world_remove:
        description: Allows you to remove a world
        default: false
    fw.world_clist:
        description: Allows you to list all registered worldclassifications
        default: false
    fw.world_list:
        description: Allows you to list all worlds
        default: false
    fw.tp:
        description: Allows you to teleport to position in a world
        default: false
